### PR TITLE
Install PSDesiredStateConfiguration module if it is not installed

### PR DESCRIPTION
**Pull request by michbern-ms**
As of PowerShell 7.2, this module is now shipped separately and must be installed explicitly.

For more details, see:
https://learn.microsoft.com/en-us/powershell/dsc/overview?view=dsc-2.0

### CODE REVIEW

**Comment by michbern-ms** [comment]
This should fix issue #602 .

**Review by jaromirk — APPROVED** [review]
I love this. Thank you for contribution!

**Comment by jaromirk** [comment]
Merged into dev branch.

**Comment by Karl-WE** [comment]
amazing! Thanks @michbern-ms /  @jaromirk.

**Pull request merged**
